# Task 1

## Q. 1 

In [1]:
def divide(a, b):
    try:
        c = a / b
    except ZeroDivisionError:
        print("Divided By Zero! Invalid Divisor")
    else:
        print("Division:", c)

In [2]:
a = int(input("Enter the Dividend:"))
b = int(input("Enter the Divisor:"))
divide(a, b)

Enter the Dividend:5
Enter the Divisor:6
Division: 0.8333333333333334


## Q. 2

In [3]:
subject = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball", "cricket"]

sentences = [(sub+" " + vb + " " + ob + ".") for sub in subject for vb in verb for ob in obj]

for sentence in sentences:
    print(sentence)

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


# Task 2

## Q. 1

In [4]:
import numpy as np

In [5]:
def power(l, N):
    x = np.array(l)
    return np.column_stack([x ** (N - 1 - i) for i in range(N)])

In [6]:
print(power([1, 2, 7, 9], 5))

[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [2401  343   49    7    1]
 [6561  729   81    9    1]]
